server:
  port: 8087

report:
  location: C:\\Temp\\reports
  cron: 0 */1 * * * *

env:
  name: Local

spring:
  application:
    name: Netherlands-Parking-System
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
